// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD725XrOaY4fEKBvdTYy-IfZpMusmvXk0U',
    appId: '1:1046336679588:web:281d279f510b560934c031',
    messagingSenderId: '1046336679588',
    projectId: 'myapp-4f4cf',
    authDomain: 'myapp-4f4cf.firebaseapp.com',
    storageBucket: 'myapp-4f4cf.appspot.com',
    measurementId: 'G-QCS4VHC562',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9r0QYWmFw3SRNnqSldcmd-xjYWQrYqT0',
    appId: '1:1046336679588:android:81262ab0a65dfffa34c031',
    messagingSenderId: '1046336679588',
    projectId: 'myapp-4f4cf',
    storageBucket: 'myapp-4f4cf.appspot.com',
  );
}
